services:
  flask:
    build: .
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/wizper.cc:/etc/ssl/wizper.cc
    depends_on:
      - web

  redis:
    image: redis:alpine
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
